#!/bin/sh

set -eu
#set -x

# Preprocess params to Windows format
args=
for arg in "$@"; do
  if echo "$arg" | fgrep -q /; then
    arg=$(echo "$arg" | tr / '\\')
  fi
  args="$args $arg"
done
set -- $args

jar=$PWD/tla2tools.jar
if test $(uname -o) = Cygwin; then
  jar=$(cygpath -w $jar)
fi

java -jar "$jar" "$@"
