#!/bin/sh

set -eu
#set -x

if test $# != 2; then
  echo >&2 "Usage: $(basename $0) spec cfg"
  exit 1
fi

# Preprocess params to Windows format
args=
for arg in "$@"; do
  if echo "$arg" | fgrep -q /; then
    arg=$(echo "$arg" | tr / '\')
  fi
  args="$args $arg"
done
set -- $args

jar='C:\Users\User\Downloads\tla2tools.jar'

java -jar "$jar" -config "$2" "$1"
